openapi: 3.0.0
info:
  description: "Our Dino Park API"
  version: 1.0.2
  title: Dino Park
  termsOfService: http://insomnia.rest/terms/
  contact:
    email: support@insomnia.rest
  license:
    name: MIT
servers:
  - url: https://mockbin.org/request/v1
tags:
  - name: dinosaurs
    description: Dinosaurs of Dino Park
paths:
  /dinosaurs:
    get:
      summary: List all Dinosaurs
      operationId: listDinosaurs
      tags:
        - dinosaurs
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of Dinosaurs
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Dinosaurs"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

    post:
      summary: Create a Dinosaur
      operationId: createDinosaur
      tags:
        - dinosaurs
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /security/fences:
    post:
      summary: Turn on/off the electricity of the fences
      operationId: securityFences
      tags:
        - security
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json: {}
components:
  schemas:
    Dinosaur:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Dinosaurs:
      type: array
      items:
        $ref: "#/components/schemas/Dinosaur"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
